### ISSUE TITLE
[102] Image BoxFit.fixWidth now requires a clipBehavior to be passed to the parent card 

### ISSUE THREAD

**Issue by ratiofu** [material-components/material-components-flutter-codelabs#130]
https://github.com/material-components/material-components-flutter-codelabs/blob/635c42bf238d94349480d6986d30a0c7a129e1b3/mdc_100_series/lib/home.dart#L47

I am new to Flutter. Working through the Material tutorial, the product images [were not being clipped at the rounded card edges](https://github.com/flutter/flutter/issues/21094):

![img_d65b4c17e0f5-1](https://user-images.githubusercontent.com/1048614/45796773-18db4500-bc57-11e8-82e8-6228cbff2c26.jpeg)

As the linked Flutter issue describes, it's now required to specify the clip behavior of the card:

```
      return Card(
+       clipBehavior: Clip.antiAlias,
        // TODO: Adjust card heights (103)
        child: Column(
```

As an aside, adding/changing that parameter and letting Hot Reload do its thing _did not_ result in the cards being repainted with the proper clipping behavior. I had to Hot Restart the app on the device to make the change stick. Perhaps I am doing something wrong or this is another (Flutter? Material?) bug.

**Comment by willlarche** [comment]
Thank you! This has been corrected in document and code.

**Comment by xpat** [comment]
Everything looks good until the final step in this second part of the codelab.  The height seems off.  The tops and bottoms are missing after adding this last piece of code:

`fit: BoxFit.fitWidth,`

Is this just particular to me since I'm doing this on an HP Chromebook and using the nami(mobile) virtual device?  Let me try it on Chrome.  Nope, same thing: missing the tops (heads of the models, for example) and bottoms of the image (legs and feet of the models, for example).  

Should I open a new issue?  @willlarche @ratiofu
