### ISSUE TITLE
Back button can also route to home on Android

### ISSUE THREAD

**Issue by xinkunZ** [material-components/material-components-flutter-codelabs#168]
* In mdc-101-flutter step5, we can use 'next' button jump to `you did it` page
* but, 'back button' can jump to `you did it` page on android too
*  how to avoid this?

**Comment by lisa-liao** [comment]
Hi @xinkunZ, thanks for your question! In the way this app is built, the "login page" sits on top of the "you did it" page, which is why the back button links to the "you did it" page. If you'd like to disable the back button, you can use the [WillPopScope class](https://api.flutter.dev/flutter/widgets/WillPopScope-class.html) as in [this page](https://stackoverflow.com/questions/45916658/how-to-deactivate-or-override-the-android-back-button-in-flutter). Hope this helps!
