### ISSUE TITLE
MDC-102 Flutter: Material Structure and Layout (Flutter) - Image not Listed

### ISSUE THREAD

**Issue by TejaDroid** [material-components/material-components-flutter-codelabs#42]
Hello, 
I am integrate full project with using the codelabs instruction, there app running well but does not shows any of images,
let any body know, what the wrong with me in code.

**Comment by MrSCAN** [comment]
Is not your code, I think 
the image assets wasn't uploaded

**Comment by TejaDroid** [comment]
Nothing has been change then also there not visible images, else working fine. the project same as repository.

**Comment by willlarche** [comment]
Hi, @TejaDroid . Sorry you're having trouble. I'll look into this right now.

**Comment by willlarche** [comment]
The images used in Shrine exist in an outside package called `shrine_images` that's hosted by Dart pub at [https://pub.dartlang.org/packages/shrine_images](https://pub.dartlang.org/packages/shrine_images). The `pubspec.yaml` file for the codelabs includes a reference to this dependency that causes it to be downloaded during `packages get` or `packages upgrade` which happens when you restart your project.
![screen shot 2018-06-22 at 10 37 59 am](https://user-images.githubusercontent.com/1271525/41791359-619c859e-760a-11e8-8491-3a6e1f956e86.png)

The `pubspec.yaml` file also has each of the files from that package listed by name so the app knows which images need to be treated as assets. In 102, the code that reads these images is in `home.dart` in the `_buildGridCards()` function when an `Image` widget is added as a child to the `AspectRatio` widget:
![screen shot 2018-06-22 at 10 43 22 am](https://user-images.githubusercontent.com/1271525/41791420-8f63e04e-760a-11e8-972e-9fc946e641a9.png)

You're instructed to add code for loading these images during 102's 6th step "Make a card collection":
![screen shot 2018-06-22 at 10 46 28 am](https://user-images.githubusercontent.com/1271525/41791121-a7e06b16-7609-11e8-9f28-ed8459850aea.png)

Make sure you didn't forget to do that or forget to add the line `package: product.assetPackage,`. Without that property, the app won't know which package the images are in.

You can also compare what you have against what's in the branch called `103-starter_and_102-complete`. This code should match what you have when you complete every instruction in the 102 codelab.

**Comment by willlarche** [comment]
Make sure your flutter SDK is up to date. Try running “flutter upgrade” in
terminal.

**Comment by WillGeller** [comment]
I am still having this exact issue, even when running right off the `103-starter_and_102-complete` branch.

Here is the result of `flutter upgrade`

``` flutter upgrade
Upgrading Flutter from /Users/willgeller/Documents/house-work/Flutter-Dev/flutter...
From https://github.com/flutter/flutter
 * [new branch]          Hixie-patch-2 -> origin/Hixie-patch-2
   c1de12dd4..70791c308  master        -> origin/master
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (8 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

Running "flutter packages upgrade" in mdc_100_series...      4.6s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13 17A365, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

**Comment by willlarche** [comment]
Sorry about that!

I need some more info:

1. Are you running this from inside Android Studio or at the terminal with `flutter run`?
2. Does the console spit out any errors related to the images?

**Comment by WillGeller** [comment]
Funny, Images load fine when I run on my actual device! But, they don't show up when running in my Android Simulator. 

No console errors related to images, I am using VS-Code as my editor and same result whether hitting run in the debugger or `flutter run` in the terminal.

**Comment by willlarche** [comment]
So, the Flutter team is interested in this since there's nothing obviously wrong. I'd love it if you could give some more information:

What OS is your computer?
Which model of phone are you emulating?
Is your Android Studio up-to-date?

**Comment by WillGeller** [comment]
- OS X High Sierra v10.13
- Emulating Pixel 2 XL API 26:5554
- Android Studio v3.1.3

*Update* I actually went and updated the packages within Android Studio and it looks like the emulator was out of date. After that updated the images show up.

Feel free to close. 
PS. Flutter is awesome!

![image](https://user-images.githubusercontent.com/6643010/43481181-36941eb0-94d3-11e8-8e70-cd277018347e.png)

**Comment by willlarche** [comment]
Oh awesome! Thanks so much for letting me know and for using Flutter!

**Comment by Nyxie12** [comment]
Hi there, I have the same issue. Unable to see image. Irony is same code works fine on windows machine running with android simulator while does not show on mac with iOs Simulator. 


![image](https://user-images.githubusercontent.com/43681947/79186058-95f47f00-7de6-11ea-9baa-bcd35c22a357.png)

![image](https://user-images.githubusercontent.com/43681947/79186091-adcc0300-7de6-11ea-8690-79210afef878.png)
