### ISSUE TITLE
Add backdrop Menu Issue

### ISSUE THREAD

**Issue by iamjavademon** [material-components/material-components-flutter-codelabs#89]
After completing '4. Add backdrop menu' using same codebase i cloned from MDC 1 which i built  by following all instructions didnt have same screenshot shown which has a pink background as shown below
<img width="335" alt="screen shot 2018-08-02 at 11 39 05 am" src="https://user-images.githubusercontent.com/14841906/43579211-268d58fc-9649-11e8-9448-a81377135b60.png"> only to go to the next step to see that the screen still remains white after adding a shape.

**Comment by michdud** [comment]
Hi @iamjavademon! Thanks for reaching out. 

To clarify, is the problem that the background is white instead of pink? 

If that's the case, it might be that you didn't pass a color to the `Container` in `app.dart`:
`home: Backdrop(`
  `// ...`
`  backLayer: Container(color: kShrinePink100),`
  `// ...`
`),`

If that's not it, please let me know and I can take a closer look! It might be helpful to see your version of `app.dart` for more context.

**Comment by iamjavademon** [comment]
Hi michdud,
   Thanks for the swift response. That isnt the problem. I have that in app.dart. i think the problem is that HomePage background isnt transparent because if i swap them(BackDrop and HomePage) the whole screen is pink. I didnt clone the code at the begining of the code lab as i was using what i already worked on from previous code lab.

**Comment by michdud** [comment]
Do you think you could send a copy of your version of the codelab, either by putting it on GitHub or sending a zip file? That would help me take a closer look and figure out what's going on with the HomePage. Thanks!

**Comment by willlarche** [comment]
Closing since we haven't heard from you. If you write back with your code, I'll reopen!
